### ISSUE TITLE
Revisit how we talk about Support Article content

### ISSUE THREAD

**Issue by annikakrilov** [AshleyHenry15/writing#17]
Where should the docs live section includes the following description of Support article content: "[Support articles](https://support.posit.co/hc/en-us) | Content that may be too specific for a product guide, workarounds, specific environment configurations, FAQS, etc. Please stop and consider if the content is truly a support article or if it belongs in a product guide."

Given the ongoing Support article consolidation effort, do we want to revise or change this at all?

**Comment by AshleyHenry15** [comment]
Removed this entry from the list completely - can revisit later
