### ISSUE TITLE
Revisit how we discuss tenses/phrases like "Will be"

### ISSUE THREAD

**Issue by annikakrilov** [AshleyHenry15/writing#19]
We need to give clearer direction here. Style guide currently says "Avoid heavy use of "Will be" but some is okay" which doesn't really give any info on when/why we would want writers to use it or not. The main issue I see with "Will be" in Connect docs is constant tense switching. It can be a big passive voice issue (related - #12), but it is also a problem switching from current to future tense and devs do this switch in the docs constantly. 

We should explicitly state what tense we use in our docs (present tense is industry standard), and then give examples of future/past tense so devs/writers know what to avoid and why, and then an example of correct present tense/'will be' or adjacent examples to show what context they are correct in.

**Comment by AshleyHenry15** [comment]
https://github.com/posit-dev/product-doc-styleguide/issues/3
