### ISSUE TITLE
Baby-proof style guide

### ISSUE THREAD

**Issue by annikakrilov** [AshleyHenry15/writing#20]
What I mean by baby-proof is to go through the guide assuming a new writer or dev has no background in our docs/we don't know what we don't know. We can add brief statements on a lot of tools/things we use in docs and link out to fuller sources (mkdocs/Quarto docs, MMoS, etc) since we don't need to rehash what's already documented, but let writers know what tools are available and when they should be used.

Things like:

- [ ] Redirects - https://quarto.org/docs/websites/website-navigation.html#redirects
- [ ] Snippets
- [ ] Templates

And, quick links for commonly searched for tasks, eg:

- [ ] How to add images
- [ ] How to add links

(will add more to these lists later)

**Comment by AshleyHenry15** [comment]
https://github.com/posit-dev/product-doc-styleguide/issues/2
